# Generated by Django 3.0.8 on 2021-11-07 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gendre', models.CharField(max_length=20, verbose_name='Жандр')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('author', models.CharField(max_length=20, verbose_name='Автор')),
                ('text', models.CharField(default='', max_length=2000000, verbose_name='Текст книги')),
                ('book_image', models.ImageField(default='', upload_to='bookimage/', verbose_name='Изображение')),
                ('public_active', models.BooleanField(default=False, verbose_name='Проверенная книга')),
                ('public', models.BooleanField(default=False, verbose_name='Публичная книга')),
                ('additions', models.ManyToManyField(blank=True, default=None, related_name='addition', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Percent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=0, verbose_name='Процент прочитаного')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Процент прочитаного',
                'verbose_name_plural': 'Проценты прочитаного',
            },
        ),
    ]
